In [6]:
import gym
import torch
from Model import *

In [7]:
env = gym.make("Breakout-v4")

/home/wyq/anaconda3/lib/python3.9/site-packages/gym/envs/registration.py:505: UserWarning: WARN: The environment Breakout-v4 is out of date. You should consider upgrading to version `v5` with the environment ID `ALE/Breakout-v5`.
  logger.warn(
/home/wyq/anaconda3/lib/python3.9/site-packages/gym/utils/seeding.py:138: DeprecationWarning: WARN: Function `hash_seed(seed, max_bytes)` is marked as deprecated and will be removed in the future. 
  deprecation(
/home/wyq/anaconda3/lib/python3.9/site-packages/gym/utils/seeding.py:175: DeprecationWarning: WARN: Function `_bigint_from_bytes(bytes)` is marked as deprecated and will be removed in the future. 
  deprecation(


In [8]:
env.action_space

Discrete(4)

In [9]:
unwrapped_env = env.unwrapped

In [10]:
env.reset()
initial_ram_state = unwrapped_env.ale.getRAM()
initial_ram_state.size

128

In [11]:
action = env.action_space.sample()
next_state, reward, done, info = env.step(action)
next_ram_state = unwrapped_env.ale.getRAM()
next_ram_state

/home/wyq/anaconda3/lib/python3.9/site-packages/gym/utils/seeding.py:47: DeprecationWarning: WARN: Function `rng.randint(low, [high, size, dtype])` is marked as deprecated and will be removed in the future. Please use `rng.integers(low, [high, size, dtype])` instead.
  deprecation(


array([ 63,  63,  63,  63,  63,  63, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 192, 192, 192, 192, 192, 192, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 240,   0,   0,
       255,   0,   0, 240,   0,   5,   0,   0,   6,   0,  70, 182, 134,
       198,  22,  38,  54,  70, 106,   3, 139,   0,   5,   0,   0,   0,
         0,   0,   0, 241,   0, 242,   0, 242,  25, 241,   5, 242,   3,
         0, 255,   0, 225,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   8,   0, 255, 255, 255, 255, 255, 255, 255,
         0,   0,   5,   0,   0, 186, 214, 117, 246, 219, 242], dtype=uint8)

In [12]:
cnet = Critic()
state_tensor = torch.tensor(next_ram_state, dtype=torch.float32)
cout = cnet(state_tensor)
cout

tensor([-8.2339], grad_fn=<AddBackward0>)

In [13]:
anet = ActorSoftmax(10, 4)
action_tensor = torch.tensor(next_ram_state, dtype=torch.float32)
aout = anet(action_tensor)
aout

tensor([[0.2255, 0.2259, 0.2480, 0.3006]], grad_fn=<SoftmaxBackward0>)